### ISSUE TITLE
Sauce Connect Action 1.1.2 timeouts

### ISSUE THREAD

**Issue by tamasmagyar** [saucelabs/sauce-connect-action#25]
After updating from 1.1.1 to 1.1.2 Sauce tunnel timeouts
Works with 1.1.1: 
```
- name: Sauce Connect Proxy Action
        uses: saucelabs/sauce-connect-action@v1.1.1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: env.TUNNEL_IDENTIFIER
```
Working example with 1.1.1:
![image](https://user-images.githubusercontent.com/20069588/110756367-62b2ae00-824a-11eb-8f86-1f342f5530b4.png)

After updating to 1.1.2 it timeouts:

```
- name: Sauce Connect Proxy Action
        uses: saucelabs/sauce-connect-action@v1.1.2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: env.TUNNEL_IDENTIFIER
```
Timeout example: 
![image](https://user-images.githubusercontent.com/68733766/110755212-fdaa8880-8248-11eb-9ad2-e0544aacb909.png)
