### ISSUE TITLE
configFile option does not mount config file on docker

### ISSUE THREAD

**Issue by alisonrclarke** [saucelabs/sauce-connect-action#32]
Actions setup:

```yaml
    - name: Setup Sauce Connect
      uses: saucelabs/sauce-connect-action@v1
      with:
        username: ${{ secrets.SAUCE_USERNAME }}
        accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
        tunnelIdentifier: ${{ github.run_id }}
        scVersion: 4.6.5
        configFile: sc-config.yml
```

Config file:

```yaml
logfile: "sauce-connect-log.txt"
verbose: 1
rest-url: "https://eu-central-1.saucelabs.com/rest/v1"
```

Logs show that the docker command is:

```bash
/usr/bin/docker run --network=host --detach -v /tmp/sauce-connect-action95C2ov:/opt/sauce-connect-action --rm saucelabs/sauce-connect:4.6.5 --logfile=/opt/sauce-connect-action/sauce-connect.log --pidfile=/srv/sauce-connect.pid --readyfile=/opt/sauce-connect-action/sc.ready --user=*** --api-key=*** --config-file=sc-config.yml --tunnel-identifier=***
```

The [sauce connect docker README](https://github.com/saucelabs/sauce-connect-docker#using-sauceconnect-config-file) says that the config file needs to be mounted but this doesn't seem to be done.

This is causing a timeout when attempting to start Sauce Connect:

```
...[9 previous attempts]
Warning: Error occurred on attempt 9 (timeout: SC was not ready even after we wait 60 secs). Retrying in 20000 ms...
/usr/bin/docker pull saucelabs/sauce-connect:4.6.5
4.6.5: Pulling from saucelabs/sauce-connect
Digest: sha256:c448b64dbd8084c60a68da8fcc01b8cd9a7d8ec349d5108df143c5f974c6bd98
Status: Image is up to date for saucelabs/sauce-connect:4.6.5
docker.io/saucelabs/sauce-connect:4.6.5
/usr/bin/docker run --network=host --detach -v /tmp/sauce-connect-action4MuWfy:/opt/sauce-connect-action --rm saucelabs/sauce-connect:4.6.5 --logfile=/opt/sauce-connect-action/sauce-connect.log --pidfile=/srv/sauce-connect.pid --readyfile=/opt/sauce-connect-action/sc.ready --user=*** --api-key=*** --config-file=sc-config.yml --tunnel-identifier=967107985
fcb8b14def8c8b5ef2fb83d6eb9cc035b4d864016f48684b4667a401eba2475b
Trying to stop the docker container with ID fcb8b14def8c8b5ef2fb83d6eb9cc035b4d864016f48684b4667a401eba2475b...
/usr/bin/docker ps -q -f id=fcb8b14def8c8b5ef2fb83d6eb9cc035b4d864016f48684b4667a401eba2475b
Container not running.
Done.
```

Thank you!
