### ISSUE TITLE
Sauce Connect Action not working like docker run in GHA Workflow

### ISSUE THREAD

**Issue by nodlesh** [saucelabs/sauce-connect-action#48]
I'm not getting the same results working with this action. I have a workflow that has a couple of agents that run in docker that needs to communicate to the app in Sauce Labs. Locally and in the GHA when I use docker run like this, everything works perfectly. 
```
       - name: run-sauce-connect-tunnel
         run: |
           docker run \
             -e SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }} \
             -e SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }} \
             --network="host" \
             --detach \
             saucelabs/sauce-connect
```

However, when I use the Sauce Connect Action, things don't work. 
```
      - name: run-sauce-connect-tunnel
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-action-tunnel
```

This is the output from the sauce connect action
```
Status: Downloaded newer image for saucelabs/sauce-connect:4.8.0
[40](https://github.com/nodlesh/aries-mobile-test-harness/runs/6656940550?check_suite_focus=true#step:4:41)
docker.io/saucelabs/sauce-connect:4.8.0
[41](https://github.com/nodlesh/aries-mobile-test-harness/runs/6656940550?check_suite_focus=true#step:4:42)
/usr/bin/docker run --network=host --detach -v /tmp/sauce-connect-actionQdhlLf:/opt/sauce-connect-action --rm saucelabs/sauce-connect:4.8.0 --logfile=/opt/sauce-connect-action/sauce-connect.log --pidfile=/srv/sauce-connect.pid --readyfile=/opt/sauce-connect-action/sc.ready --user=*** --api-key=*** --tunnel-identifier=github-action-tunnel
[42](https://github.com/nodlesh/aries-mobile-test-harness/runs/6656940550?check_suite_focus=true#step:4:43)
8ed09834ed6e2566b4e5183dec58e3b67c3f0bdb7790b3eec3bda9b7608f7849
[43](https://github.com/nodlesh/aries-mobile-test-harness/runs/6656940550?check_suite_focus=true#step:4:44)
SC ready
```

What am I missing here?
