### ISSUE TITLE
SAUCE_CONNECT_DIR_IN_HOST in environment is not set. Allow overriding where sauce-connect.log is exported.

### ISSUE THREAD

**Issue by Noraldeno** [saucelabs/sauce-connect-action#89]
## Expected Behavior

Per README, `${{ env.SAUCE_CONNECT_DIR_IN_HOST }}` environment variable should be set to allow user to access log file after `sauce-connect-action` is ran.

Also, can we update to allow user to set where sauce-connect.log is exported?

## Actual Behavior

`${{ env.SAUCE_CONNECT_DIR_IN_HOST }}` is not exported and is empty after `sauce-connect-action` is ran.

## Steps to Reproduce the Problem

  1. Run `sauce-connect-action`
  2. Echo `${{ env.SAUCE_CONNECT_DIR_IN_HOST }}` in the next step

```yaml
jobs:
    test:
        runs-on: ubuntu-latest
        name: Action Test
        steps:
            # ...
            - uses: actions/checkout@v3
            - uses: saucelabs/sauce-connect-action@v2
              with:
                  username: ${{ secrets.SAUCE_USERNAME }}
                  accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
                  tunnelName: github-action-tunnel
            # ...

            - run: echo ${{ env.SAUCE_CONNECT_DIR_IN_HOST }} # Empty directory
```

## Specifications

  - Version: 2.3.7
  - Platform: Ubuntu
